### ISSUE TITLE
fix(jans-cedarling): add missing fields on LogEntry struct

### ISSUE THREAD

**Issue by rmarinn** [JanssenProject/jans#10296]
**Is your feature request related to a problem? Please describe.**

Tests won't run because of the following errors:

```sh
error[E0063]: missing fields `cedar_lang_version` and `cedar_sdk_version` in initializer of `log_entry::LogEntry`
   --> cedarling/src/log/stdout_logger.rs:102:25
    |
102 |         let log_entry = LogEntry {
    |                         ^^^^^^^^ missing `cedar_lang_version` and `cedar_sdk_version`

error[E0063]: missing fields `cedar_lang_version` and `cedar_sdk_version` in initializer of `log_entry::LogEntry`
  --> cedarling/src/log/test.rs:68:17
   |
68 |     let entry = LogEntry {
   |                 ^^^^^^^^ missing `cedar_lang_version` and `cedar_sdk_version`

error[E0063]: missing fields `cedar_lang_version` and `cedar_sdk_version` in initializer of `log_entry::LogEntry`
   --> cedarling/src/log/test.rs:145:21
    |
145 |     let log_entry = LogEntry {
    |                     ^^^^^^^^ missing `cedar_lang_version` and `cedar_sdk_version`
```

I ran git bisect and seems like this is caused by commit [20ed1733a8ae7baa88f4c644caa08f81b3059f8e](https://github.com/JanssenProject/jans/commit/20ed1733a8ae7baa88f4c644caa08f81b3059f8e)

**Describe the solution you'd like**

we just need to update the `LogEntry` structs used on tests to have the new fields. It seems like setting them to `None` would be enough.

```rs
let log_entry = LogEntry {
    id: uuid7(),
    time: SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("Time went backwards")
        .as_secs(),
    log_kind: LogType::Decision,
    pdp_id: uuid7(),
    application_id: Some("test_app".to_string().into()),
    auth_info: None,
    msg: "Test message".to_string(),
    error_msg: None,

    // add these two
    cedar_lang_version: None,
    cedar_sdk_version: None,
}
```
