### PR TITLE
fix(jans-auth-server): compilation failure after merge

### LINKED ISSUE #7553: fix(jans-auth-server): compilation failure after merge
**Describe the bug**

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:4.0.0-M7:site (default-site) on project jans-auth-server-parent: Failed to get report for org.apache.maven.plugins:maven-javadoc-plugin: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project jans-auth-server: Compilation failure
[ERROR] /home/jetty/.jenkins/workspace/jans-auth-server/jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TxTokenService.java:[32,36] cannot find symbol
[ERROR]   symbol:   class TokenEntity
[ERROR]   location: package io.jans.as.server.model.ldap
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### PR DESCRIPTION
**Pull request by yuriyz**
### Description

fix(jans-auth-server): compilation failure after merge

#### Target issue
  
closes #7553

### CODE REVIEW

**Review by moabu — APPROVED** [review]

**Comment by mo-auto** [comment]
Error: Hi @yuriyz, You did not reference an open issue in your [PR](7554). I attempted to create an [issue](#7557) for you.    
 Please update that [issues'](#7557) title and body and make sure I correctly referenced it in the above PRs body.
