### ISSUE TITLE
unable to pass data parameter for creating custom scripts

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#434]
Running the below after building from `master` branch gives an unhandled error.
```
python3 jans-cli-linux-amd64.pyz --host <FQDN> --client-id $TESTCLIENT --client_secret $TESTCLIENTSECRET --operation-id post-config-scripts --data /tmp/sampleadd.json \
--cert-file jans_cli_client.crt --key-file jans_cli_client.key
```

ERROR:

```
An Unhandled error raised: process_command_post() got an unexpected keyword argument 'data'
```

This is working in `v0.1.1`
