### PR TITLE
fix(jans-auth-server): external libraries unavaiable from Java Interception Script #11377

### LINKED ISSUE #11377: fix(jans-auth): Extern Libraries unavaiable from Interception Script
**Describe the bug**
I have a custom jar file in `/opt/jans/jetty/jans-auth/custom/libs/` which contains code accessed by multiple interception scripts.
When deploying a java interception script using that library, I get the following compilation error the jans-auth_script.log:
`Generated:15: error: package ch.fhnw.imvs.ai.aura does not exist`
The listed package is in the custom jar.
This worked earlier (still is in use and working on a server using 1.4.0), but it no longer does work in my local development setup (using the monolith). Itried with 0.0.0-nightly and 1.5.0 

**To Reproduce**
1. Download scripts and yaml files according to [https://docs.jans.io/v1.5.0/janssen-server/install/docker-install/compose/](https://docs.jans.io/v1.5.0/janssen-server/install/docker-install/compose/)
2. Put a custom jar file into `jans-auth-custom`
3. Execute up.sh
4. After the server has finished installation deploy a java interception script that imports the package deployed in the jar
5. Open the `jans-auth-log/jans-auth_script.log` file to see the error

**Expected behavior**
Interception script should be able to access the libraries in `/opt/jans/jetty/jans-auth/custom/libs/` as described in [https://docs.jans.io/v1.5.0/janssen-server/developer/interception-scripts/#implementation-in-pure-java](https://docs.jans.io/v1.5.0/janssen-server/developer/interception-scripts/#implementation-in-pure-java)

**Desktop:**
Docker Version: 4.40.0
Janssen Version: 1.5.0

**Additional context**
For reproducing I used a jar file with a single class that had a single static method returning a String. My interception script for reproducing was a UpdateToken script, that imported the class in the jar file and logged the result of the static method in the init method, but beside that did nothing (except for implementing the interface with dummy methods that simply return null, false, .... methods)
I deployed the script over the REST interface of the config API.

### PR DESCRIPTION
**Pull request by yuriyz**
### Description

fix(jans-auth-server): external libraries unavaiable from Java Interception Script 

#### Target issue
  
closes #11377

### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

### CODE REVIEW

**Comment by mo-auto** [comment]
### :tada: **Snyk checks have passed. No issues have been found so far.**

:white_check_mark: **security/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/janssenproject/pr-checks/03bd42e8-5547-4346-b5e0-8f76cd72e647?refs=e4cb8f5d53d7e0cb1e52f9c68536f351b52031c7&source=prChecksComment)

**Review by yuriyzz — APPROVED** [review]

**Review by yurem — APPROVED** [review]
