### PR TITLE
fix(jans-config-api): config-api compilation failed in main #2030

### LINKED ISSUE #2030: fix(jans-config-api): config-api compilation failed in main
**Describe the bug**

image

### PR DESCRIPTION
**Pull request by yuriyz**
docs: no docs

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
closes #2030

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [] Relevant unit and integration tests have been added/updated
- [  Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @yuriyz, You did not reference an open issue in your [PR](2031). I attempted to create an [issue](#2032) for you.    
 Please update that [issues'](#2032) title and body and make sure I correctly referenced it in the above PRs body.
