### ISSUE TITLE
fix(jans-auth): Extern Libraries unavaiable from Interception Script

### ISSUE THREAD

**Issue by tawaren** [JanssenProject/jans#11377]
**Describe the bug**
I have a custom jar file in `/opt/jans/jetty/jans-auth/custom/libs/` which contains code accessed by multiple interception scripts.
When deploying a java interception script using that library, I get the following compilation error the jans-auth_script.log:
`Generated:15: error: package ch.fhnw.imvs.ai.aura does not exist`
The listed package is in the custom jar.
This worked earlier (still is in use and working on a server using 1.4.0), but it no longer does work in my local development setup (using the monolith). Itried with 0.0.0-nightly and 1.5.0 

**To Reproduce**
1. Download scripts and yaml files according to [https://docs.jans.io/v1.5.0/janssen-server/install/docker-install/compose/](https://docs.jans.io/v1.5.0/janssen-server/install/docker-install/compose/)
2. Put a custom jar file into `jans-auth-custom`
3. Execute up.sh
4. After the server has finished installation deploy a java interception script that imports the package deployed in the jar
5. Open the `jans-auth-log/jans-auth_script.log` file to see the error

**Expected behavior**
Interception script should be able to access the libraries in `/opt/jans/jetty/jans-auth/custom/libs/` as described in [https://docs.jans.io/v1.5.0/janssen-server/developer/interception-scripts/#implementation-in-pure-java](https://docs.jans.io/v1.5.0/janssen-server/developer/interception-scripts/#implementation-in-pure-java)

**Desktop:**
Docker Version: 4.40.0
Janssen Version: 1.5.0

**Additional context**
For reproducing I used a jar file with a single class that had a single static method returning a String. My interception script for reproducing was a UpdateToken script, that imported the class in the jar file and logged the result of the static method in the init method, but beside that did nothing (except for implementing the interface with dummy methods that simply return null, false, .... methods)
I deployed the script over the REST interface of the config API.

**Comment by yuriyz** [comment]
We need @yurem @devrimyatar to help on this. If it works in 1.4.0 and stopped in nightly build then it sounds as jetty 12 related.

**Comment by yurem** [comment]
I've tested in our latest version and it works well.
Here how I tested.
1. Create test.jar
```
org
  gluu
    Test.java
        package org.gluu;

        public class Test {
          public void sayHello() {
              System.out.println("Hello!");
          }
    }
```
3. `javac -source 17 -target 17 org/gluu/Test.java`
Force to use java 17 because we release with jdk 17.
5. `jar -cf test.jar .`
6. Put `test.jar` into `/opt/jans/jetty/jans-auth/custom/libs`
7. No changes to `/opt/jans/jetty/jans-auth/webapps/jans-auth.xml` is needed because it specify to include all libs by default:
```
<Set name="extraClasspath">/opt/jans/jetty/jans-auth/custom/libs/*</Set></Configure>
```
9. Add to basic or any other script:
```
from org.gluu import Test
...
Test().sayHello()

```
11.  Check if there is string `Hello!` in `/opt/jans/jetty/jans-auth/logs/<date>.jetty.log `

**Comment by tawaren** [comment]
Thanks for looking into it.
I followed your instructions and it worked with a python script.
However, when switching back to java i get the error (during compilation of the script)
`error: package org.gluu does not exist`


Used Python script (works):

```
from io.jans.model.custom.script.type.token import UpdateTokenType

from org.gluu import Test

class UpdateToken(UpdateTokenType):

    def __init__(self, currentTimeMillis):
        self.currentTimeMillis = currentTimeMillis

    def init(self, customScript, configurationAttributes):
        Test().sayHello()
        print "INIT HAS RUN"
        return True

    def destroy(self, configurationAttributes):
        return True

    def getApiVersion(self):
        return 11
```


Used Java script (Import fails):


```
import io.jans.model.SimpleCustomProperty;
import io.jans.model.custom.script.model.CustomScript;
import io.jans.model.custom.script.type.token.UpdateTokenType;
import io.jans.service.custom.script.CustomScriptManager;

import java.util.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.gluu.Test;

public class UpdateToken implements UpdateTokenType {
    private static final Logger log = LoggerFactory.getLogger(CustomScriptManager.class);

    @Override
    public boolean init(Map<String, SimpleCustomProperty> configurationAttributes) {
	Test t = new Test();
        t.sayHello();
        log.info("INIT HAS RUN");
        return true;
    }

    @Override
    public boolean init(CustomScript customScript, Map<String, SimpleCustomProperty> configurationAttributes) {
        return init(configurationAttributes);
    }

    @Override
    public boolean destroy(Map<String, SimpleCustomProperty> configurationAttributes) {
        return true;
    }

    @Override
    public int getApiVersion() {
        return 11;
    }

    @Override
    public boolean modifyIdToken(Object jsonWebResponse, Object tokenContext){
        return true;
    }

    @Override
    public boolean modifyAccessToken(Object accessToken, Object tokenContext){
        return true;
    }

    @Override
    public boolean modifyRefreshToken(Object refreshToken, Object tokenContext){
        return true;
    }

    @Override
    public int getRefreshTokenLifetimeInSeconds(Object tokenContext){
        return 0;
    }

    @Override
    public int getIdTokenLifetimeInSeconds(Object tokenContext){
        return 0;
    }
	
    @Override
    public int getAccessTokenLifetimeInSeconds(Object tokenContext){
        return 0;
    }
}
```

**Comment by yuriyz** [comment]
Java source code compiler builds classpath here:
[JIT compiler](https://github.com/JanssenProject/jans/blob/49a6476f4262fc89458a9a53538bafd439f4561b/jans-core/script/src/main/java/io/jans/service/custom/script/jit/SimpleJavaCompiler.java#L107)
Strange that it stopped to work.

**Comment by yuriyz** [comment]
Would you please share libraries which you put in `/opt/jans/jetty/jans-auth/custom/libs/` and also you java script ?
Also if you restart AS, does it print any errors? Please attach `jans-auth.log`. We suspect classloader problem but it's not clear from where it comes.

**Comment by yuriyz** [comment]
It's not clear what is wrong. `classpath` is good. Sounds that after jetty 12 java 17 upgrade built-in `javax.tools.JavaCompiler` refuses to recognize external jars even if it's in classpath. 

![Image](https://github.com/user-attachments/assets/98f8d724-dd5c-4e38-87b7-241a13dde336)
